name: Comment on Merged PR

on:
  pull_request:
    types:
      - closed

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: 'This PR was successfully merged!'
            });
