name: Comment on Merged PR

on:
  pull_request:
    types:
      # - closed
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'

      - name: Run Julia script
        id: julia_script
        run: |
          julia script.jl
