name: Comment on Merged PR

on:
  pull_request:
    types:
      - closed

# on:
#   pull_request:
#     branches: [ main ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Run Julia script
        id: julia_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_event_pull_request_number: ${{ github.event.pull_request.number}}
          gitbub_event_pull_request_user_login: ${{ github.event.pull_request.user.login }}
          github_repository: ${{ github.repository}}
        run: |
          julia script.jl
          echo "::set-output name=exit_code::$?"

      # - name: Comment on PR
      #   uses: actions/github-script@v5
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       const issue_number = context.issue.number;
      #       const owner = context.repo.owner;
      #       const repo = context.repo.repo;
      #       const pr_author = context.payload.pull_request.user.login;
      #       const exit_code = steps.julia_script.outputs.exit_code;
      #       const message = exit_code == 0 ? 'pass' : 'fail';
      #       await github.rest.issues.createComment({
      #         owner: owner,
      #         repo: repo,
      #         issue_number: issue_number,
      #         body: `@${pr_author}, The Julia script result: ${message}`
      #       });


